name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup java 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        architecture: x64
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build AmongCord
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        scripts/build.sh --jar
    - name: release info
      id: relInfo
      run: |
        echo "::set-output name=date::$(date +'%H:%M %m/%d/%Y')"
        echo "::set-output name=shortHash::$(git rev-parse --short HEAD)"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.run_number }}"
        prerelease: false
        title: "AmongCord ${{ steps.relInfo.outputs.date }} ${{ steps.relInfo.outputs.shortHash }}"
        files: ./AmongCord-Proxy/bootstrap/target/AmongCord.jar
